"$schema" = "https://starship.rs/config-schema.json"

command_timeout = 1500

format = """
[](fg:color_bg1)\
$os\
$username\
$hostname\
[ ](fg:color_bg1 bg:color_bg2)\
$directory\
[ ](fg:color_bg2 bg:color_bg3)\
$git_branch\
$git_status\
[ ](fg:color_bg3 bg:color_bg4)\
$c\
$dotnet\
$java\
$kotlin\
$nodejs\
[ ](fg:color_bg4 bg:color_bg5)\
$cmd_duration\
[ ](fg:color_bg5)\
\n$character\
"""

palette = "ccswe_dark"

[palettes.ccswe_dark]
color_bg1 = "#A61F96"
color_bg2 = "#8e1a80"
color_bg3 = "#741669"
color_bg4 = "#5a1152"
color_bg5 = "#400c3a"

color_red = "#fe1c57"
color_green = "#2ed8a2"
color_yellow = "#f2d16b"
color_gray = "#aaaaaa"
color_white = "#cccccc"

[character]
error_symbol = "[❯](bold color_red)"
success_symbol = "[❯](bold color_green)"

[cmd_duration]
format = "[$duration](bg:color_bg5 fg:color_gray)"
min_time = 500

[directory]
style = "bg:color_bg2 fg:color_white"
format = "[$path]($style)"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:color_bg3 fg:color_yellow"
format = "[$symbol $branch]($style)"

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
deleted = ""
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = '[( $all_status$ahead_behind)]($style)'
style = "bold bg:color_bg3 fg:color_red"

[hostname]
format = "[@$hostname]($style)"
ssh_only = true
ssh_symbol = " "
style = "bg:color_bg1 fg:color_white"

[os]
format = "[$symbol]($style)"
style = "bg:color_bg1 fg:color_white"
disabled = false

[username]
disabled = false
format = "[$user]($style)"
show_always = false
style_root = "bg:color_bg1 fg:color_red"
style_user = "bg:color_bg1 fg:color_white"

# Code symbols
[c]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#6295CB"
symbol = " "

[dotnet]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#1180C3"
symbol = " "

[java]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#F7901E"
symbol = " "

[kotlin]
format = '[$symbol]($style)'
style = "bg:color_bg4 fg:#C017E4"
symbol = " "

[nodejs]
style = "bg:color_bg4 fg:#5FA04E"
format = '[$symbol($version)]($style)'
symbol = " "

# OS Symbols
[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "